### ISSUE TITLE
Enable consistent eslint rules for app

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#58]
As discussed in #53, let's turn on `no-explicit-any` and `no-default-export` in app. We should try to make the rules as consistent as possible with the top-level `.eslintrc` so when we actually do a migration, we won't end up with a ton of errors.

**Comment by alexdanilowicz** [comment]
@Teddarific just curious why do you want a global eslint? Is that how you've seen other industry-grade monorepos? Is it because that is the very _purpose_ of a monorepo: to have consitent settings like that ? 

-------
Anyway, 

<img width="823" alt="Screen Shot 2021-02-04 at 10 06 16 PM" src="https://user-images.githubusercontent.com/29822597/106996459-e6521a00-6735-11eb-9125-25bbd1c374c3.png">

FYI currently , `/app/`'s eslint works great in VSCODE when you ONLY open the `app/` directory in vscode, i.e., only if you do 
`cd ~/leftonread/app && code .`

if you do `cd ~/leftonread && code .` and go to a `app/` file within vscode, eslint throws errors because I think its' looking at the global eslint? I've seen this issue before in monorepos where there's multiple eslints... it's a whole mess. This was the solution I did last time so I'll look into it and solving it this way https://github.com/Microsoft/vscode-eslint/issues/310

**Comment by alexdanilowicz** [comment]
I'll need to explore where to put the .vscode/settings.json when I do this issue.

I'm surprised you don't care for vscode settings. I can't live without them. The search excludes setting is fantastic! @Teddarific

**Comment by alexdanilowicz** [comment]
@Teddarific bump on question here: https://github.com/Left-on-Read/leftonread/issues/58#issuecomment-773818388

**Comment by Teddarific** [comment]
Very purpose of the monorepo, and when you're working across projects, it would be good to have a consistent set of standards and expectations IMO. It would feel weird to be able to use `any` in one project, and not another if that makes sense. 

This task should be easier now that `eslint-config` exists. This task changes into add `extends: @leftonread/eslint-config` to the .eslint config in /app/, and clean duplicate rules and only keep rules specific to the app directory (e.g. lint rules specific to electron).
